// Utility for handling product images with fallbacks
export const getProductImageSrc = (product, fallbackType = 'svg') => {
  // Try to get the main image or first image from the product
  const primaryImage = product?.mainImage?.url || 
                      product?.images?.[0]?.url || 
                      product?.image;

  if (primaryImage) {
    return primaryImage;
  }

  // Fallback options
  if (fallbackType === 'data') {
    // Base64 encoded SVG placeholder - always works
    return 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPCEtLSBCYWNrZ3JvdW5kIC0tPgogIDxyZWN0IHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjZjNmNGY2Ii8+CiAgCiAgPCEtLSBUZWEgY3VwIG91dGxpbmUgLS0+CiAgPHBhdGggZD0iTTEyMCAxODBDMTIwIDE2NSAxMzAgMTUwIDE1MCAx NTBIMjUwQzI3MCAxNTAgMjgwIDE2NSAyODAgMTgwVjIyMEMyODAgMjM1IDI3MCAyNTAgMjUwIDI1MEgxNTBDMTMwIDI1MCAxMjAgMjM1IDEyMCAyMjBWMTgwWiIgc3Ryb2tlPSIjZDFkNWRiIiBzdHJva2Utd2lkdGg9IjMiIGZpbGw9IiNmZmZmZmYiLz4KICA8IS0tIFRlYSBjdXAgaGFuZGxlIC0tPgogIDxwYXRoIGQ9Ik0yODAgMTcwQzI5MCAxNzAgMzAwIDE4MCAzMDAgMTkwVjIwMEMzMDAgMjEwIDI5MCAyMjAgMjgwIDIyMCIgc3Ryb2tlPSIjZDFkNWRiIiBzdHJva2Utd2lkdGg9IjMiIGZpbGw9Im5vbmUiLz4KICA8IS0tIFRlYSBpbiBjdXAgLS0+CiAgPHBhdGggZD0iTTEyNSAxODBDMTI1IDE3MCAxMzMgMTYwIDE1MCAxNjBIMjUwQzI2NyAxNjAgMjc1IDE3MCAyNzUgMTgwVjIxNUMyNzUgMjI1IDI2NyAyMzUgMjUwIDIzNUgxNTBDMTMzIDIzNSAxMjUgMjI1IDEyNSAyMTVWMTgwWiIgZmlsbD0iI2U1OWUzYiIgb3BhY2l0eT0iMC43Ii8+CiAgPCEtLSBTdGVhbSBsaW5lcyAtLT4KICA8cGF0aCBkPSJNMTcwIDE0MEMxNzAgMTM1IDE3NSAxMzAgMTc1IDEyNUMxNzUgMTIwIDE3MCAxMTUgMTcwIDExMCIgc3Ryb2tlPSIjZDFkNWRiIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIvPgogIDxwYXRoIGQ9Ik0yMDAgMTQwQzIwMCAxMzUgMjA1IDEzMCAyMDUgMTI1QzIwNSAxMjAgMjAwIDExNSAyMDAgMTEwIiBzdHJva2U9IiNkMWQ1ZGIiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIi8+CiAgPHBhdGggZD0iTTIzMCAxNDBDMjMwIDEzNSAyMzUgMTMwIDIzNSAxMjVDMjM1IDEyMCAyMzAgMTE1IDIzMCAxMTAiIHN0cm9rZT0iI2QxZDVkYiIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiLz4KICA8IS0tIFRlYSB0ZXh0IC0tPgogIDx0ZXh0IHg9IjIwMCIgeT0iOTAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5Y2EzYWYiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIyNCIgZm9udC13ZWlnaHQ9ImJvbGQiPlRFQTwvdGV4dD4KICA8dGV4dCB4PSIyMDAiIHk9IjI4MCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzljYTNhZiIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE0Ij5JbWFnZSBub3QgYXZhaWxhYmxlPC90ZXh0Pgo8L3N2Zz4=';
  }

  // Default SVG file fallback
  return '/images/tea-placeholder.svg';
};

// Error handler for images
export const handleImageError = (event, fallbackSrc) => {
  const img = event.target;
  
  // Don't loop if already using data URL
  if (img.src.includes('data:image')) {
    return;
  }
  
  // Try provided fallback first, then SVG, then data URL
  if (fallbackSrc && img.src !== fallbackSrc) {
    img.src = fallbackSrc;
  } else if (!img.src.includes('tea-placeholder.svg')) {
    img.src = '/images/tea-placeholder.svg';
  } else {
    // Ultimate fallback: data URL that always works
    img.src = DEFAULT_PRODUCT_IMAGE;
  }
};

// Default fallback image (data URL)
export const DEFAULT_PRODUCT_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPCEtLSBCYWNrZ3JvdW5kIC0tPgogIDxyZWN0IHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjZjNmNGY2Ii8+CiAgCiAgPCEtLSBUZWEgY3VwIG91dGxpbmUgLS0+CiAgPHBhdGggZD0iTTEyMCAxODBDMTIwIDE2NSAxMzAgMTUwIDE1MCAx NTBIMjUwQzI3MCAxNTAgMjgwIDE2NSAyODAgMTgwVjIyMEMyODAgMjM1IDI3MCAyNTAgMjUwIDI1MEgxNTBDMTMwIDI1MCAxMjAgMjM1IDEyMCAyMjBWMTgwWiIgc3Ryb2tlPSIjZDFkNWRiIiBzdHJva2Utd2lkdGg9IjMiIGZpbGw9IiNmZmZmZmYiLz4KICA8IS0tIFRlYSBjdXAgaGFuZGxlIC0tPgogIDxwYXRoIGQ9Ik0yODAgMTcwQzI5MCAxNzAgMzAwIDE4MCAzMDAgMTkwVjIwMEMzMDAgMjEwIDI5MCAyMjAgMjgwIDIyMCIgc3Ryb2tlPSIjZDFkNWRiIiBzdHJva2Utd2lkdGg9IjMiIGZpbGw9Im5vbmUiLz4KICA8IS0tIFRlYSBpbiBjdXAgLS0+CiAgPHBhdGggZD0iTTEyNSAxODBDMTI1IDE3MCAxMzMgMTYwIDE1MCAxNjBIMjUwQzI2NyAxNjAgMjc1IDE3MCAyNzUgMTgwVjIxNUMyNzUgMjI1IDI2NyAyMzUgMjUwIDIzNUgxNTBDMTMzIDIzNSAxMjUgMjI1IDEyNSAyMTVWMTgwWiIgZmlsbD0iI2U1OWUzYiIgb3BhY2l0eT0iMC43Ii8+CiAgPCEtLSBTdGVhbSBsaW5lcyAtLT4KICA8cGF0aCBkPSJNMTcwIDE0MEMxNzAgMTM1IDE3NSAxMzAgMTc1IDEyNUMxNzUgMTIwIDE3MCAxMTUgMTcwIDExMCIgc3Ryb2tlPSIjZDFkNWRiIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIvPgogIDxwYXRoIGQ9Ik0yMDAgMTQwQzIwMCAxMzUgMjA1IDEzMCAyMDUgMTI1QzIwNSAxMjAgMjAwIDExNSAyMDAgMTEwIiBzdHJva2U9IiNkMWQ1ZGIiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIi8+CiAgPHBhdGggZD0iTTIzMCAxNDBDMjMwIDEzNSAyMzUgMTMwIDIzNSAxMjVDMjM1IDEyMCAyMzAgMTE1IDIzMCAxMTAiIHN0cm9rZT0iI2QxZDVkYiIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiLz4KICA8IS0tIFRlYSB0ZXh0IC0tPgogIDx0ZXh0IHg9IjIwMCIgeT0iOTAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5Y2EzYWYiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIyNCIgZm9udC13ZWlnaHQ9ImJvbGQiPlRFQTwvdGV4dD4KICA8dGV4dCB4PSIyMDAiIHk9IjI4MCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzljYTNhZiIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE0Ij5JbWFnZSBub3QgYXZhaWxhYmxlPC90ZXh0Pgo8L3N2Zz4=';
